"""edit recurringtask model

Revision ID: 9b7f07bddf07
Revises: fcf0d26d0c1c
Create Date: 2026-05-07 11:08:30.849565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7f07bddf07'
down_revision = 'fcf0d26d0c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
