"""fix recurring

Revision ID: fcf0d26d0c1c
Revises: ba79af8d4b31
Create Date: 2026-05-06 16:19:19.198419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf0d26d0c1c'
down_revision = 'ba79af8d4b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_user',
    sa.Column('recurring_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('recurring_id', 'user_id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recurring_task', ['recurring_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recurring_id')

    op.drop_table('recurring_user')
    op.drop_table('recurring_task')
    # ### end Alembic commands ###
